[project]
name = "insight-streamlit"
version = "0.1.0"
description = "Semantic search over the Baha'i Writings"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.97.0",
    "pinecone>=7.3.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.0",
]
